# Paul Osting

# PA_8

# A

In [3]:
import numpy as np
list1=[10,20,30,40]
array1=np.array(list1)
array1=array1.reshape(2,2)
array1

array([[10, 20],
       [30, 40]])

# i

In [4]:
s=array1**2
s

array([[ 100,  400],
       [ 900, 1600]], dtype=int32)

# ii

In [6]:
h=array1+100
h

array([[110, 120],
       [130, 140]])

# iii

In [7]:
f=array1*5
f

array([[ 50, 100],
       [150, 200]])

# iv

In [8]:
sr=np.sqrt(array1)
sr

array([[3.16227766, 4.47213595],
       [5.47722558, 6.32455532]])

# B

In [13]:
array2=np.linspace(10,20,9)
array2=array2.reshape(3,3)
list2=[]
for i in range(3,28):
    if i%3==0:
        list2.append(i)
array3=np.array(list2)
array3=array3.reshape(3,3)

In [15]:
array4=array2+array3
array4

array([[13.  , 17.25, 21.5 ],
       [25.75, 30.  , 34.25],
       [38.5 , 42.75, 47.  ]])

# C

In [23]:
p1=np.load('process1.npy')

In [24]:
p2=np.load('process2.npy')

In [25]:
p3=np.load('process3.npy')

In [26]:
p4=np.load('process4.npy')

In [27]:
p5=np.load('process1.npy')

In [35]:
pt=np.hstack([p1,p2,p3,p4,p5])

In [37]:
pt=pt.reshape(5,5)

In [38]:
pt

array([[52, 12, 81,  0, 58],
       [96,  4, 61, 16, 43],
       [38, 96, 45, 17, 58],
       [97, 21, 22, 25,  6],
       [52, 12, 81,  0, 58]])

In [42]:
print(np.mean(pt[0]))
print(np.mean(pt[1]))
print(np.mean(pt[2]))
print(np.mean(pt[3]))
print(np.mean(pt[4]))

40.6
44.0
50.8
34.2
40.6


In [43]:
print(np.mean(pt))

42.04
